packages:
  - 'packages/*'

catalog:
  axios: '^1.6.0'
  chalk: '^5.4.1'
  commander: '^14.0.0'
  ora: '^8.2.0'
  nx: '21.2.2'
  '@nx/devkit': '21.2.2'
  '@nx/esbuild': '21.2.2'
  '@nx/eslint': '21.2.2'
  '@nx/eslint-plugin': '21.2.2'
  '@nx/jest': '21.2.2'
  '@nx/js': '21.2.2'
  '@nx/node': '21.2.2'
  '@nx/workspace': '21.2.2'